[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache = true
cache_path  = 'forge-cache'

optimizer = true
optimizer_runs = 200
via_ir = false
sparse_mode = true

verbosity = 3
ffi = false

[fuzz]
runs=256

[rpc_endpoints]
#mainnet = "${RPC_MAINNET}"
optimism = "https://mainnet.optimism.io"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
polygon_mumbai = "https://rpc.ankr.com/polygon_mumbai"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
